source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
#use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'SDWebImage', '~>3.7'

pod 'FBSDKLoginKit'

#pod 'Google/SignIn'

