module: SwiftyRequest
author: IBM
github_url: https://github.com/IBM-Swift/SwiftyRequest

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, SwiftyRequest.xcodeproj, -target, SwiftyRequest, LIBRARY_SEARCH_PATHS=.build/debug]