# source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '11.0'
use_frameworks!

target 'BluePic' do
	platform :ios, '11.0'

	pod 'BluemixAppID'

	pod 'BMSPush'

	pod 'SDWebImage', '~>3.7'

	pod 'SVProgressHUD'

end
