source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
#use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

#pod 'Alamofire', '~> 3.0'
#pod 'AlamofireObjectMapper', '~> 2.0'

pod 'CDTDatastore'

pod 'IMFFacebookAuthentication'

pod 'SDWebImage', '~>3.7'
