# Makefile
# This is a makefile that conveniently calls Kitura-net's makefile when Kitura-net is a dependency
# Should be copied to project's root directory

KITURA_NET_DIR=$(wildcard Packages/Kitura-net-*)

make:
	make -f ${KITURA_NET_DIR}/Makefile
